// src/App.jsx — Generated by VIA for: Fix the RangeError: Invalid time value crash in the expense tracker. The date field from the API is sometimes null or in an unexpected format, causing the app to go blank on load. Add a safe date formatting helper that checks if the date value is valid before formatting it, and shows a fallback like "N/A" if it's invalid. Also add a favicon.ico to fix the 404 error.
import { useState, useEffect, useCallback } from "react";
import { Routes, Route, Link, useNavigate } from "react-router-dom";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { getItems, createItem, deleteItem, getStats } from "./api.js";

const parseItems = (data) => {
  if (Array.isArray(data)) return data;
  if (data?.items   && Array.isArray(data.items))   return data.items;
  if (data?.data    && Array.isArray(data.data))    return data.data;
  if (data?.results && Array.isArray(data.results)) return data.results;
  if (data && typeof data === "object" &&
      (data.id !== undefined || data._id !== undefined)) return [data];
  return [];
};

const THEME = "#10b981";

export default function App() {
  return (
    <div className="min-h-screen" style={{ backgroundColor: "#f0fdf4" }}>
      <ToastContainer position="top-right" autoClose={3000} hideProgressBar={false} />
      <nav className="bg-white border-b border-gray-100 shadow-sm sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <Link to="/" className="flex items-center gap-2">
              <span className="text-2xl">💰</span>
              <span className="font-display font-bold text-gray-900 text-lg">Fix The Rangeerror Invalid Time Value Crash In</span>
            </Link>
            <div className="flex items-center gap-3">
              <Link to="/" className="text-sm text-gray-500 hover:text-gray-900 px-3 py-1.5 rounded-lg hover:bg-gray-50 transition-colors">Dashboard</Link>
              <Link to="/items" className="text-sm text-gray-500 hover:text-gray-900 px-3 py-1.5 rounded-lg hover:bg-gray-50 transition-colors">All Records</Link>
              <Link to="/new" className="btn-primary text-sm py-2 px-4">+ Add Expense</Link>
            </div>
          </div>
        </div>
      </nav>
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <Routes>
          <Route path="/" element={<HomePage />} />
          <Route path="/items" element={<ItemListPage />} />
          <Route path="/new" element={<ItemFormPage />} />
          <Route path="/edit/:id" element={<ItemFormPage />} />
          <Route path="*" element={<NotFoundPage />} />
        </Routes>
      </main>
    </div>
  );
}

function HomePage() {
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [items, setItems] = useState([]);
  useEffect(() => {
    Promise.all([
      getStats().then(r => r.data).catch(() => ({total: 0, active: 0})),
      getItems().then(r => parseItems(r.data)).catch(() => []),
    ]).then(([s, i]) => { setStats(s); setItems(i); setLoading(false); });
  }, []);
  return (
    <div className="space-y-8">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-3xl font-display font-bold text-gray-900">Fix The Rangeerror Invalid Time Value Crash In</h1>
          <p className="text-gray-500 mt-1 text-sm">Powered by VIA — Autonomous AI Platform</p>
        </div>
        <Link to="/new" className="btn-primary">+ Add Expense</Link>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-5">
        <StatCard title="Total Expenses" value={stats?.total ?? 0} loading={loading} color="blue" />
        <StatCard title="Active" value={stats?.active ?? 0} loading={loading} color="green" />
        <StatCard title="Tracked" value={"Auto"} loading={loading} color="purple" />
      </div>
      <div className="card">
        <div className="flex items-center justify-between mb-5">
          <h2 className="text-lg font-display font-semibold text-gray-900">Recent Records</h2>
          <Link to="/items" className="text-sm font-medium hover:underline" style={{ color: THEME }}>View all →</Link>
        </div>
        {loading ? <Spinner /> : items.length === 0 ? (
          <div className="text-center py-12">
            <p className="text-gray-400 mb-4">No expenses yet</p>
            <Link to="/new" className="btn-primary inline-block">+ Add Expense</Link>
          </div>
        ) : (
          <div className="space-y-3">
            {items.slice(0, 5).map(item => (
              <div key={item.id ?? item._id} className="flex items-center justify-between p-4 rounded-xl border border-gray-100 hover:bg-gray-50 transition-all">
                <div>
                  <p className="font-medium text-gray-900">{item.title}</p>
                  <p className="text-xs text-gray-400 mt-0.5">{item.created_at ? new Date(item.created_at).toLocaleDateString() : ""}</p>
                </div>
                <Badge status={item.status || "active"} />
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

function StatCard({ title, value, loading, color }) {
  const cls = {
    blue:   "from-blue-50 to-blue-100/50 border-blue-200 text-blue-700",
    green:  "from-green-50 to-green-100/50 border-green-200 text-green-700",
    purple: "from-purple-50 to-purple-100/50 border-purple-200 text-purple-700",
  };
  return (
    <div className={`rounded-2xl border bg-gradient-to-br p-6 ${cls[color] || cls.blue}`}>
      <p className="text-sm font-medium opacity-70">{title}</p>
      <p className="text-3xl font-display font-bold mt-2">{loading ? "..." : value}</p>
    </div>
  );
}

function ItemListPage() {
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [deleting, setDeleting] = useState(null);

  const load = useCallback(() => {
    setLoading(true);
    getItems()
      .then(r => setItems(parseItems(r.data)))
      .catch(() => setError("Cannot reach backend. It may be starting up — wait 30s and retry."))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => { load(); }, [load]);

  const handleDelete = async (id) => {
    if (!confirm("Delete this record?")) return;
    setDeleting(id);
    try {
      await deleteItem(id);
      toast.success("Deleted successfully!");
      load();
    } catch {
      toast.error("Delete failed. Please try again.");
    } finally {
      setDeleting(null);
    }
  };

  const filtered = items.filter(i => (i.title || "").toLowerCase().includes(search.toLowerCase()));
  if (loading) return <Spinner />;
  if (error) return (
    <div className="card text-center py-16">
      <p className="text-2xl mb-3">⚠️</p>
      <p className="text-red-500 font-medium mb-4">{error}</p>
      <button onClick={load} className="btn-primary">Retry</button>
    </div>
  );
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <h1 className="text-2xl font-display font-bold text-gray-900">All Records</h1>
        <div className="flex gap-3">
          <input className="input max-w-xs" placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} />
          <Link to="/new" className="btn-primary whitespace-nowrap">+ Add Expense</Link>
        </div>
      </div>
      {filtered.length === 0 ? (
        <div className="card text-center py-20">
          <p className="text-5xl mb-4">💰</p>
          <p className="text-gray-400 text-lg mb-6">No expenses yet</p>
          <Link to="/new" className="btn-primary inline-block">+ Add Expense</Link>
        </div>
      ) : (
        <div className="card overflow-hidden p-0">
          <table className="w-full text-sm">
            <thead className="bg-gray-50/80 border-b border-gray-100">
              <tr>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Title</th>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Category</th><th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Amount</th>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Status</th>
                <th className="px-5 py-3 text-right text-xs font-semibold text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {filtered.map(item => (
                <tr key={item.id ?? item._id} className="hover:bg-gray-50/50 transition-colors">
                  <td className="px-5 py-4 font-medium text-gray-900">{item.title}</td>
                  <td className="px-5 py-4 text-gray-600">{item.category || 'General'}</td><td className="px-5 py-4 font-semibold text-emerald-700">₹{(item.amount || 0).toLocaleString()}</td>
                  <td className="px-5 py-4"><Badge status={item.status || "active"} /></td>
                  <td className="px-5 py-4">
                    <div className="flex justify-end gap-2">
                      <Link to={`/edit/${item.id ?? item._id}`} className="text-xs py-1.5 px-3 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Edit</Link>
                      <button onClick={() => handleDelete(item.id ?? item._id)} disabled={deleting === (item.id ?? item._id)}
                        className="text-xs py-1.5 px-3 bg-red-50 hover:bg-red-100 text-red-600 rounded-lg border border-red-100 transition-colors disabled:opacity-50">
                        {deleting === (item.id ?? item._id) ? "..." : "Delete"}
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          <div className="px-5 py-3 bg-gray-50/50 border-t border-gray-100 text-xs text-gray-400">
            {filtered.length} record{filtered.length !== 1 ? "s" : ""}
          </div>
        </div>
      )}
    </div>
  );
}

function ItemFormPage() {
  const [form, setForm] = useState({ title: "", description: "", status: "active" });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const navigate = useNavigate();
  const submit = async (e) => {
    e.preventDefault();
    if (!form.title.trim()) { setError("Title is required"); return; }
    setLoading(true); setError("");
    try {
      await createItem(form);
      navigate("/items");
      toast.success("Saved successfully!");
    } catch (err) {
      const msg = err.response?.data?.detail || "Save failed. Backend may be starting up.";
      setError(msg);
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };
  return (
    <div className="max-w-2xl mx-auto">
      <Link to="/items" className="text-sm text-gray-500 hover:text-gray-700 mb-6 inline-block">← Back</Link>
      <div className="card">
        <h1 className="text-2xl font-display font-bold text-gray-900 mb-6">Add Expense</h1>
        {error && <div className="bg-red-50 border border-red-100 text-red-700 p-4 rounded-xl mb-5 text-sm">{error}</div>}
        <form onSubmit={submit} className="space-y-5">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Title *</label>
            <input className="input" placeholder="Enter title" value={form.title} onChange={e => setForm({...form, title: e.target.value})} required />
          </div>
          
          <div className="grid grid-cols-2 gap-4">
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Amount (₹)</label>
              <input className="input" type="number" placeholder="0.00" value={form.amount || ""} onChange={e => setForm({...form, amount: parseFloat(e.target.value) || 0})} /></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Category</label>
              <select className="input" value={form.category || "General"} onChange={e => setForm({...form, category: e.target.value})}>
                <option>General</option><option>Food</option><option>Transport</option><option>Bills</option><option>Entertainment</option>
              </select></div>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
            <textarea className="input resize-none h-24" placeholder="Optional notes..." value={form.description || ""} onChange={e => setForm({...form, description: e.target.value})} />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
            <select className="input" value={form.status} onChange={e => setForm({...form, status: e.target.value})}>
              <option value="active">Active</option><option value="inactive">Inactive</option>
              <option value="pending">Pending</option><option value="done">Done</option>
            </select>
          </div>
          <div className="flex gap-3 pt-2">
            <button type="submit" className="btn-primary" disabled={loading}>{loading ? "Saving..." : "Save"}</button>
            <Link to="/items" className="btn-secondary">Cancel</Link>
          </div>
        </form>
      </div>
    </div>
  );
}

function Badge({ status }) {
  const m = { active: "badge-active", inactive: "badge-inactive", pending: "badge-pending", done: "badge-done", scheduled: "badge-scheduled", confirmed: "badge-confirmed" };
  return <span className={m[status] || "badge-inactive"}>{status}</span>;
}

function Spinner() {
  return (
    <div className="flex flex-col items-center justify-center py-24 gap-4">
      <div className="w-10 h-10 border-4 border-gray-200 rounded-full animate-spin" style={{ borderTopColor: THEME }} />
      <p className="text-sm text-gray-400">Loading...</p>
    </div>
  );
}

function NotFoundPage() {
  return (
    <div className="card text-center py-24">
      <p className="text-8xl font-display font-bold text-gray-100">404</p>
      <p className="text-gray-400 mt-4 mb-6">Page not found</p>
      <Link to="/" className="btn-primary inline-block">Go Home</Link>
    </div>
  );
}
